name = "AStarSearch"
uuid = "e6cbe913-2b79-4cc5-848a-e3bbf8537828"
authors = ["Paolo Sarti <paolo.sarti93@gmail.com>"]
version = "0.5.4"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "^0.18"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
